### ISSUE TITLE
Trigger event without mouse up ?

### ISSUE THREAD

**Issue by jm4r7in** [rcy/meteor-nouislider#4]
Hello, Thanks for the package !
In your example, the even 'change' is triggered only after the mouse is released. Is there a way to get the value while the mouse is still down ?

**Comment by rcy** [comment]
noUISlider provides a 'slide' event, does that work for you?

http://refreshless.com/nouislider/events-callbacks/#section-slide

**Comment by jm4r7in** [comment]
That's great ! Thanks !
