### ISSUE TITLE
selector.noUiSlider.destroy() Not workong

### ISSUE THREAD

**Issue by PankajJatav** [rcy/meteor-nouislider#5]
I am trying to update the slider range dynamically.
As per the documentation example i am trying to destroy the old slider then creating new but it's show me the error the 'Cannot read property 'noUiSlider' of null'.

**Comment by rcy** [comment]
Can you post some code of what you are trying?

**Comment by PankajJatav** [comment]
Basically i am trying to destroy the old slider and initialize the new slider, So my range and can change.
Here my code.
$("#mySlider").noUiSlider.destroy() or $("#mySlider").noUiSlider().destroy() 
$("#mySlider").noUiSlider({
            start: [x,y],
            range:{
                min: x,
                max: y,
            } ,
            step: 1,
        })

**Comment by andr33a** [comment]
I have the same issue. I have defined a new template for the slider so I can use it on different pages and I have the same problem. The code: 
```javascript
Template.slider.destroyed = function() {
  this.$("#slider").noUiSlider.destroy();
 }
```
throws the following error:
```
TypeError: this.$(...).noUiSlider.destroy is not a function
    at Template.slider.destroyed (slider.js?58f4268f843fe18600ff59a7d4e6b890e9459735:24)
    at template.js:116
    at Function.Template._withTemplateInstanceFunc (template.js:437)
    at fireCallbacks (template.js:112)
    at null.<anonymous> (template.js:218)
    at fireCallbacks (view.js:267)
    at Object.Tracker.nonreactive (tracker.js:560)
    at view.js:264
    at Object.Blaze._withCurrentView (view.js:523)
    at Object.Blaze._fireCallbacks (view.js:263)
```

**Comment by PankajJatav** [comment]
Hey @andr33a 
You can manually destroy the slider.
Just remove the class and content that added by the Slider.
Like this:
$('#slider').empty();
$('#slider').removeAttr('class');

@rcy Can you please add a function which can only remove the class those are added by the noUiSlider and remove inner html of the div.
Please don't forgot to check where div have noUiSlider created or not.

If @rcy  you are busy now day then i will fix this by this weekend.
